# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'cytiodriver' do
  #Firebase and RNFirebase pods
  pod 'Firebase/Core', '~> 5.3.0'

  # Required by RNFirebase
  pod 'Firebase/Database', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'
  
  pod 'Fabric'
  pod 'Crashlytics'
end
