# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'driverapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for driverapp
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Database', '~> 5.3.0'

  target 'driverapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'driverappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
